apiVersion: v1
kind: Service
metadata:
  name: rails
  labels:
    name: app
    tier: application
spec:
  selector:
    app: app
  type: NodePort
  ports:
  - port: 8080
    targetPort: 3000
    protocol: TCP
    name: http