apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        imagePullPolicy: IfNotPresent
